r01lib: P3T1755 Class Reference
P3T1755 Class Reference
#include <P3T1755.h>
Public Types
enum registers { Temp , Conf , T_LOW , T_HIGH }
Public Member Functions
P3T1755 (I2C &i2c, uint8_t address=P3T1755_ADDR_I2C)
~P3T1755 ()
float temp (void)
void conf (uint8_t conf)
uint8_t conf (void)
void high (float temp)
float high (void)
void low (float temp)
float low (void)
void write (uint8_t reg, float v)
int16_t read (uint8_t reg)
void info (void)
operator float ()
Public Member Functions inherited from I3C_Device
I3C_Device (I2C &i2c, uint8_t address)
~I3C_Device ()
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Static Public Member Functions
static float short2celsius (int16_t v)
static int16_t celsius2short (float v)
static int16_t swap_bytes (int16_t v)
Additional Inherited Members
Protected Attributes inherited from I3C_Device
I2C & _i2c
uint8_t _addr
Detailed Description
Definition at line 30 of file P3T1755.h.
Member Enumeration Documentation
registers
enum P3T1755::registers
Enumerator
Temp
Conf
T_LOW
T_HIGH
Definition at line 33 of file P3T1755.h.
Constructor & Destructor Documentation
P3T1755()
P3T1755::P3T1755 (I2C & i2c, uint8_t address = P3T1755_ADDR_I2C)
Definition at line 37 of file P3T1755.cpp.
~P3T1755()
P3T1755::~P3T1755 ()
Definition at line 38 of file P3T1755.cpp.
Member Function Documentation
celsius2short()
int16_t P3T1755::celsius2short (float v) static
Definition at line 126 of file P3T1755.cpp.
conf() [1/2]
void P3T1755::conf (uint8_t conf)
Definition at line 45 of file P3T1755.cpp.
References I3C_Device::_addr, I3C_Device::_i2c, Conf, and I2C::reg_write().
conf() [2/2]
uint8_t P3T1755::conf (void)
Definition at line 50 of file P3T1755.cpp.
References I3C_Device::_addr, I3C_Device::_i2c, Conf, and I2C::reg_read().
high() [1/2]
void P3T1755::high (float temp)
Definition at line 58 of file P3T1755.cpp.
References T_HIGH, and write().
high() [2/2]
float P3T1755::high (void)
Definition at line 63 of file P3T1755.cpp.
References read(), short2celsius(), and T_HIGH.
info()
void P3T1755::info (void)
Definition at line 92 of file P3T1755.cpp.
References I3C_Device::ccc_get(), celsius2short(), conf(), DIRECT_GETBCR, DIRECT_GETDCR, DIRECT_GETPID, high(), low(), P3T1755_ADDR_I3C, I3C::PID_LENGTH, and temp().
low() [1/2]
void P3T1755::low (float temp)
Definition at line 68 of file P3T1755.cpp.
References T_LOW, and write().
low() [2/2]
float P3T1755::low (void)
Definition at line 73 of file P3T1755.cpp.
References read(), short2celsius(), and T_LOW.
operator float()
P3T1755::operator float ()
A short hand for reading pins
Definition at line 140 of file P3T1755.cpp.
read()
int16_t P3T1755::read (uint8_t reg)
Definition at line 84 of file P3T1755.cpp.
References I3C_Device::_addr, I3C_Device::_i2c, and I2C::reg_read().
short2celsius()
float P3T1755::short2celsius (int16_t v) static
Definition at line 121 of file P3T1755.cpp.
References swap_bytes().
swap_bytes()
int16_t P3T1755::swap_bytes (int16_t v) static
Definition at line 131 of file P3T1755.cpp.
temp()
float P3T1755::temp (void)
Definition at line 40 of file P3T1755.cpp.
References read(), short2celsius(), and Temp.
write()
void P3T1755::write (uint8_t reg, float v)
Definition at line 78 of file P3T1755.cpp.
References I3C_Device::_addr, I3C_Device::_i2c, celsius2short(), I2C::reg_write(), and swap_bytes().
The documentation for this class was generated from the following files:
r01device/temp_sensor/P3T1755.h
r01device/temp_sensor/P3T1755.cpp