r01lib: r01device/rtc/tzcode/strptime.c File Reference
strptime.c File Reference
#include "private.h"
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "localedef.h"
#include "tzfile.h"
#include "strptime.h"
Macros
#define DEF_WEAK(sym) /* */
#define _ctloc(x) (_CurrentTimeLocale->x)
#define _ALT_E 0x01
#define _ALT_O 0x02
#define _LEGAL_ALT(x) { if (alt_format & ~(x)) return (0); }
#define FIELD_TM_MON (1 << 0)
#define FIELD_TM_MDAY (1 << 1)
#define FIELD_TM_WDAY (1 << 2)
#define FIELD_TM_YDAY (1 << 3)
#define FIELD_TM_YEAR (1 << 4)
Functions
static int _conv_num (const unsigned char **, int *, int, int)
static int epoch_to_tm (const unsigned char **, struct tm *)
static int leaps_thru_end_of (const int y)
static char * _strptime (const char *, const char *, struct tm *, int)
static const u_char * _find_string (const u_char *, int *, const char *const *, const char *const *, int)
char * strptime (const char *buf, const char *fmt, struct tm *tm)
DEF_WEAK (strptime)
Variables
static char gmt [] = { "GMT" }
static char utc [] = { "UTC" }
static const char *const nast [5]
static const char *const nadt [5]
static const int mon_lengths [2][MONSPERYEAR]
Macro Definition Documentation
_ALT_E
#define _ALT_E 0x01
Definition at line 69 of file strptime.c.
_ALT_O
#define _ALT_O 0x02
Definition at line 70 of file strptime.c.
_ctloc
#define _ctloc (x) (_CurrentTimeLocale->x)
Definition at line 63 of file strptime.c.
_LEGAL_ALT
#define _LEGAL_ALT (x) { if (alt_format & ~(x)) return (0); }
Definition at line 71 of file strptime.c.
DEF_WEAK
#define DEF_WEAK (sym) /* */
Definition at line 50 of file strptime.c.
FIELD_TM_MDAY
#define FIELD_TM_MDAY (1 << 1)
Definition at line 77 of file strptime.c.
FIELD_TM_MON
#define FIELD_TM_MON (1 << 0)
Definition at line 76 of file strptime.c.
FIELD_TM_WDAY
#define FIELD_TM_WDAY (1 << 2)
Definition at line 78 of file strptime.c.
FIELD_TM_YDAY
#define FIELD_TM_YDAY (1 << 3)
Definition at line 79 of file strptime.c.
FIELD_TM_YEAR
#define FIELD_TM_YEAR (1 << 4)
Definition at line 80 of file strptime.c.
Function Documentation
_conv_num()
static int _conv_num (const unsigned char ** buf, int * dest, int llim, int ulim) static
Definition at line 614 of file strptime.c.
_find_string()
static const u_char * _find_string (const u_char * bp, int * tgt, const char *const * n1, const char *const * n2, int c) static
Definition at line 664 of file strptime.c.
_strptime()
static char * _strptime (const char * buf, const char * fmt, struct tm * tm, int initialize) static
Definition at line 113 of file strptime.c.
References _ALT_E, _ALT_O, _conv_num(), _ctloc, _find_string(), _LEGAL_ALT, _strptime(), DAYSPERNYEAR, DAYSPERWEEK, epoch_to_tm(), EPOCH_WDAY, EPOCH_YEAR, FIELD_TM_MDAY, FIELD_TM_MON, FIELD_TM_WDAY, FIELD_TM_YDAY, FIELD_TM_YEAR, gmt, isleap, leaps_thru_end_of(), mon_lengths, MONSPERYEAR, nadt, nast, SECSPERHOUR, SECSPERMIN, TM_YEAR_BASE, and utc.
DEF_WEAK()
DEF_WEAK (strptime)
epoch_to_tm()
static int epoch_to_tm (const unsigned char ** buf, struct tm * tm) static
Definition at line 637 of file strptime.c.
leaps_thru_end_of()
static int leaps_thru_end_of (const int y) static
Definition at line 686 of file strptime.c.
References leaps_thru_end_of().
strptime()
char * strptime (const char * buf, const char * fmt, struct tm * tm)
Definition at line 106 of file strptime.c.
References _strptime().
Variable Documentation
gmt
char gmt[] = { "GMT" } static
Definition at line 82 of file strptime.c.
mon_lengths
const int mon_lengths[2][MONSPERYEAR] static
Initial value:
= {
        { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 },
        { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
}
Definition at line 92 of file strptime.c.
nadt
const char* const nadt[5] static
Initial value:
= {
       "EDT",    "CDT",    "MDT",    "PDT",    "\0\0\0"
}
Definition at line 88 of file strptime.c.
nast
const char* const nast[5] static
Initial value:
= {
       "EST",    "CST",    "MST",    "PST",    "\0\0\0"
}
Definition at line 85 of file strptime.c.
utc
char utc[] = { "UTC" } static
Definition at line 83 of file strptime.c.