r01lib: PCF2131_I2C Class Reference
PCF2131_I2C Class Reference
#include <RTC_NXP.h>
Public Types
enum reg_num {
Control_1 , Control_2 , Control_3 , Control_4 ,
Control_5 , SR_Reset , _100th_Seconds , Seconds ,
Minutes , Hours , Days , Weekdays ,
Months , Years , Second_alarm , Minute_alarm ,
Hour_alarm , Day_alarm , Weekday_alarm , CLKOUT_ctl ,
Timestp_ctl1 , Sec_timestp1 , Min_timestp1 , Hour_timestp1 ,
Day_timestp1 , Mon_timestp1 , Year_timestp1 , Timestp_ctl2 ,
Sec_timestp2 , Min_timestp2 , Hour_timestp2 , Day_timestp2 ,
Mon_timestp2 , Year_timestp2 , Timestp_ctl3 , Sec_timestp3 ,
Min_timestp3 , Hour_timestp3 , Day_timestp3 , Mon_timestp3 ,
Year_timestp3 , Timestp_ctl4 , Sec_timestp4 , Min_timestp4 ,
Hour_timestp4 , Day_timestp4 , Mon_timestp4 , Year_timestp4 ,
Aging_offset , INT_A_MASK1 , INT_A_MASK2 , INT_B_MASK1 ,
INT_B_MASK2 , Watchdg_tim_ctl , Watchdg_tim_val
}
enum periodic_int_select { DISABLE , EVERY_SECOND , EVERY_MINUTE }
enum timestanp_setting { LAST , FIRST }
Public Types inherited from PCF2131_base
enum reg_num {
Control_1 , Control_2 , Control_3 , Control_4 ,
Control_5 , SR_Reset , _100th_Seconds , Seconds ,
Minutes , Hours , Days , Weekdays ,
Months , Years , Second_alarm , Minute_alarm ,
Hour_alarm , Day_alarm , Weekday_alarm , CLKOUT_ctl ,
Timestp_ctl1 , Sec_timestp1 , Min_timestp1 , Hour_timestp1 ,
Day_timestp1 , Mon_timestp1 , Year_timestp1 , Timestp_ctl2 ,
Sec_timestp2 , Min_timestp2 , Hour_timestp2 , Day_timestp2 ,
Mon_timestp2 , Year_timestp2 , Timestp_ctl3 , Sec_timestp3 ,
Min_timestp3 , Hour_timestp3 , Day_timestp3 , Mon_timestp3 ,
Year_timestp3 , Timestp_ctl4 , Sec_timestp4 , Min_timestp4 ,
Hour_timestp4 , Day_timestp4 , Mon_timestp4 , Year_timestp4 ,
Aging_offset , INT_A_MASK1 , INT_A_MASK2 , INT_B_MASK1 ,
INT_B_MASK2 , Watchdg_tim_ctl , Watchdg_tim_val
}
enum periodic_int_select { DISABLE , EVERY_SECOND , EVERY_MINUTE }
enum timestanp_setting { LAST , FIRST }
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF2131_I2C (I2C &interface, uint8_t i2c_address=(0xA6 > > 1))
virtual ~PCF2131_I2C ()
time_t time (time_t *tp)
void begin (void)
bool oscillator_stop (void)
time_t rtc_time (void)
void set (struct tm *now_tm)
void alarm (alarm_setting digit, int val)
void alarm (alarm_setting digit, int val, int int_sel)
void alarm_clear (void)
void alarm_disable (void)
void timestamp (int num, timestanp_setting ts_setting, int int_sel=0)
time_t timestamp (int num)
uint8_t int_clear (void)
uint8_t int_clear (uint8_t *state_p)
void periodic_interrupt_enable (periodic_int_select sel, int int_sel=0)
void reg_w (uint8_t reg_adr, uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t data)
void reg_r (uint8_t reg_adr, uint8_t *data, int size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Public Member Functions inherited from PCF2131_base
PCF2131_base ()
virtual ~PCF2131_base ()
void alarm (alarm_setting digit, int val, int int_sel)
void timestamp (int num, timestanp_setting ts_setting, int int_sel=0)
time_t timestamp (int num)
uint8_t int_clear (uint8_t *state_p)
void periodic_interrupt_enable (periodic_int_select sel, int int_sel=0)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
~I2C_device ()
void repeated_start_enable (bool en=true)
bool ping (void)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
Private Member Functions
void _reg_w (uint8_t reg, uint8_t *vp, int len)
void _reg_r (uint8_t reg, uint8_t *vp, int len)
void _reg_w (uint8_t reg, uint8_t val)
uint8_t _reg_r (uint8_t reg)
void _bit_op8 (uint8_t reg, uint8_t mask, uint8_t val)
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t stop=128)
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Detailed Description
PCF2131_I2C class
PCF2131 class driver using I2C interface
Definition at line 266 of file RTC_NXP.h.
Member Enumeration Documentation
periodic_int_select
enum PCF2131_I2C::periodic_int_select
Periodic interrupt selection descriptor
Enumerator
DISABLE
EVERY_SECOND
EVERY_MINUTE
Definition at line 296 of file RTC_NXP.h.
reg_num
enum PCF2131_I2C::reg_num
Name of the PCF2131 registers
Enumerator
Control_1
Control_2
Control_3
Control_4
Control_5
SR_Reset
_100th_Seconds
Seconds
Minutes
Hours
Days
Weekdays
Months
Years
Second_alarm
Minute_alarm
Hour_alarm
Day_alarm
Weekday_alarm
CLKOUT_ctl
Timestp_ctl1
Sec_timestp1
Min_timestp1
Hour_timestp1
Day_timestp1
Mon_timestp1
Year_timestp1
Timestp_ctl2
Sec_timestp2
Min_timestp2
Hour_timestp2
Day_timestp2
Mon_timestp2
Year_timestp2
Timestp_ctl3
Sec_timestp3
Min_timestp3
Hour_timestp3
Day_timestp3
Mon_timestp3
Year_timestp3
Timestp_ctl4
Sec_timestp4
Min_timestp4
Hour_timestp4
Day_timestp4
Mon_timestp4
Year_timestp4
Aging_offset
INT_A_MASK1
INT_A_MASK2
INT_B_MASK1
INT_B_MASK2
Watchdg_tim_ctl
Watchdg_tim_val
Definition at line 281 of file RTC_NXP.h.
timestanp_setting
enum PCF2131_I2C::timestanp_setting
Timestamp setting descriptor
Enumerator
LAST
FIRST
Definition at line 302 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF2131_I2C()
PCF2131_I2C::PCF2131_I2C (I2C & interface, uint8_t i2c_address = (0xA6 >> 1))
Create a PCF2131_I2C instance connected to specified I2C pins with specified address
Parameters
interface I2C instance
i2c_address I2C-bus address (default: (0xBC>>1))
Definition at line 3 of file PCF2131_I2C.cpp.
~PCF2131_I2C()
PCF2131_I2C::~PCF2131_I2C () virtual
Destructor
Definition at line 7 of file PCF2131_I2C.cpp.
Member Function Documentation
_bit_op8()
void PCF2131_I2C::_bit_op8 (uint8_t reg, uint8_t mask, uint8_t val) private virtual
Proxy method for interface
Implements PCF2131_base.
Definition at line 31 of file PCF2131_I2C.cpp.
References bit_op8().
_reg_r() [1/2]
uint8_t PCF2131_I2C::_reg_r (uint8_t reg) private virtual
Proxy method for interface
Implements PCF2131_base.
Definition at line 26 of file PCF2131_I2C.cpp.
References reg_r().
_reg_r() [2/2]
void PCF2131_I2C::_reg_r (uint8_t reg, uint8_t * vp, int len) private virtual
Proxy method for interface
Implements PCF2131_base.
Definition at line 16 of file PCF2131_I2C.cpp.
References reg_r().
_reg_w() [1/2]
void PCF2131_I2C::_reg_w (uint8_t reg, uint8_t * vp, int len) private virtual
Proxy method for interface
Implements PCF2131_base.
Definition at line 11 of file PCF2131_I2C.cpp.
References reg_w().
_reg_w() [2/2]
void PCF2131_I2C::_reg_w (uint8_t reg, uint8_t val) private virtual
Proxy method for interface
Implements PCF2131_base.
Definition at line 21 of file PCF2131_I2C.cpp.
References reg_w().
alarm() [1/2]
void PCF2131_I2C::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Reimplemented from PCF2131_base.
alarm() [2/2]
void PCF2131_I2C::alarm (alarm_setting digit, int val, int int_sel)
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
alarm_clear()
void PCF2131_I2C::alarm_clear (void) virtual
Alarm interrupt disable
Reimplemented from PCF2131_base.
alarm_disable()
void PCF2131_I2C::alarm_disable (void) virtual
Interrupt clear
Reimplemented from PCF2131_base.
begin()
void PCF2131_I2C::begin (void) virtual
Initializer Just clears penginf interrupt
Reimplemented from PCF2131_base.
bit_op8()
void PCF2131_I2C::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
int_clear() [1/2]
uint8_t PCF2131_I2C::int_clear (uint8_t * state_p)
Interrupt clear
int_clear() [2/2]
uint8_t PCF2131_I2C::int_clear (void) virtual
Interrupt clear
Reimplemented from PCF2131_base.
oscillator_stop()
bool PCF2131_I2C::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Reimplemented from PCF2131_base.
periodic_interrupt_enable()
void PCF2131_I2C::periodic_interrupt_enable (periodic_int_select sel, int int_sel = 0)
Enabling every second/minute interrupt
Parameters
sel choose DISABLE, EVERY_SECOND or EVERY_MINUTE in 'enum periodic_int_select'
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
read_r8()
uint8_t PCF2131_I2C::read_r8 (uint8_t reg)
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
reg_r() [1/2]
uint8_t PCF2131_I2C::reg_r (uint8_t reg_adr)
Single register read
Parameters
reg register index/address/pointer
Returns
read data
reg_r() [2/2]
void PCF2131_I2C::reg_r (uint8_t reg_adr, uint8_t * data, int size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
void PCF2131_I2C::reg_w (uint8_t reg_adr, uint8_t * data, int size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [2/2]
void PCF2131_I2C::reg_w (uint8_t reg_adr, uint8_t data)
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
rtc_time()
time_t PCF2131_I2C::rtc_time (void) virtual
time
Returns
time_t value of current time
Reimplemented from PCF2131_base.
set()
void PCF2131_I2C::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Reimplemented from PCF2131_base.
time()
time_t PCF2131_I2C::time (time_t * tp)
time
"time()" in "time.h" compatible method for RTC
Parameters
tp pointer to time_t variable
Returns
time_t value of current time
timestamp() [1/2]
time_t PCF2131_I2C::timestamp (int num)
Getting timestamp info
Parameters
num timestamp number: 1~4
Returns
time_t
timestamp() [2/2]
void PCF2131_I2C::timestamp (int num, timestanp_setting ts_setting, int int_sel = 0)
Timestamp setting
Parameters
num timestamp number: 1~4
ts_setting event recording option. Choose LAST or FIRST in 'enum timestanp_setting'
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
write_r8()
void PCF2131_I2C::write_r8 (uint8_t reg, uint8_t val)
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF2131_I2C.cpp